---
title: 'Canopy cover over time'
author: "Kelly Loria"
date: "`r Sys.Date()`"
output:
   html_document:
    theme: united
    highlight: tango
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
body, td {font-size: 12px;}
code.r{font-size: 8px;}
pre {font-size: 10px}
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F, message = F)
#knitr::opts_knit$set(root.dir = 'C/Users/kloria/Documents/Davis_data_exploration/')
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})

```

```{r, echo = F, message = F}
### Packages
#setwd("C/Users/kloria/Documents/Davis_data_exploration/")

library(tidyverse)
library(lubridate)
library(dataRetrieval)
library(viridis)
library(cowplot)
library(zoo)
library(readxl)
library(ggpubr)
library(knitr)
library(kableExtra)
library(plotly)
library(readxl)
library(ggpmisc)

site_colors <- c(
  "Ophir" = "#7d5ba6",
  "Winters" = "#4287f5",
  "Winters upstream" = "#7fc5f0",
  "Davis" = "#d9cb7c",
  "Browns" = "#c94d00", 
  "Browns sub"  = "#bd772d"
)


site_lab_colors <- c(
  "ophir" = "#7d5ba6",
    "ophir_hw" = "#7d1ba6",
  "winters_usgs" = "#4287f5",
  "winters_up" = "#7fc5f0",
  "davis" = "#d9cb7c",
  "browns" = "#c94d00", 
  "browns_sub"  = "#bd772d",
   "browns_hw"  = "#bd272d"
)


```


```{r, eval=TRUE, echo = F, error=FALSE, warning=FALSE, message=FALSE}
##### Function for water year:
# fxn for water year
water_year <- function(data) {
  data %>%
    mutate(date = ymd(date)) %>%
    mutate(WaterYear = if_else(month(date) >= 10, year(date) + 1, year(date)))
}
```



```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}
# Chem data
davis_data <- read.csv("/Users/kellyloria/Documents/DRI/ERDC_Davis_Fire/Raw_data/CanpoyCover1.csv") %>% mutate(date = as.Date(date, format = c("%m/%d/%Y"))) %>%
    mutate(site_lab = case_when(
    Site== "Davis" ~ "davis", 
    Site == "Ophir " ~ "ophir",
    Site == "Ophir HW" ~ "ophir_hw",
    Site == "Winters" ~ "winters_usgs",
    Site == "Winters USGS" ~ "winters_usgs",
    Site == "Winters up" ~ "winters_up",
    Site == "Browns" ~ "browns", 
    Site == "Browns HW" ~ "browns_hw",
    Site == "Browns sub" ~ "browns_sub",
    Site == "Browns Sub" ~ "browns_sub"))
names(davis_data)

str(davis_data)
```

### Collective site canpoy cover 

```{r, warning=F, size = 'small', echo=FALSE, fig.width=8, fig.height=3}

p1 <- davis_data %>%
  ggplot(aes(x = site_lab,
             y = canpoy.cover.percent)) +
  geom_boxplot(aes(fill=site_lab), alpha = 0.75) +
  geom_point(
    alpha = 0.8, size = 2, 
    aes(color = site_lab),
    position = position_jitter(width = 0.1),  
    shape = 19) +
  scale_fill_manual(values = site_lab_colors) +
  scale_color_manual(values = site_lab_colors) +
  labs(y = "Canopy cover (%)", x = NULL) +
  guides(shape = "none") +
  theme_minimal()

p1

```



```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}


davis_dat <- davis_data %>%
  group_by(site_lab, date) %>%
  summarise(
    mean_cc_per = mean(canpoy.cover.percent, na.rm = TRUE),
    sd_cc = sd(canpoy.cover.percent, na.rm = TRUE),
    .groups = "drop"
  )

```


### Mean and standard deviation of Canopy cover at each reach per visit. 

August to October 2025

```{r, warning=F, size = 'small', echo=FALSE, fig.width=8, fig.height=3}

# Plot means ± SD
p2 <- davis_dat %>%
  filter(!(site_lab== "browns_hw"| site_lab== "ophir_hw"))%>% 
  ggplot(aes(x = date, y = mean_cc_per, color = site_lab, group = site_lab)) +
  geom_point(size = 3) +
  geom_line() +
  geom_errorbar(
    aes(ymin = mean_cc_per - sd_cc, ymax = mean_cc_per + sd_cc),
    width = 0.1,
    position = position_dodge(width = 0.2)
  ) +
  scale_color_manual(values = site_lab_colors) +
  labs(
    y = "Canopy Cover (%) ± SD",
    x = NULL) +
  theme_minimal()

p2

```

```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}
# write.csv(davis_dat, "/Users/kellyloria/Documents/DRI/ERDC_Davis_Fire/Processes_data/CanopyCover_QAQC.csv")
```

End script.

