---
title: 'YSI water quality for pack fire and davis fire macros'
author: "Kelly Loria"
date: "`r Sys.Date()`"
output:
   html_document:
    theme: united
    highlight: tango
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
body, td {font-size: 12px;}
code.r{font-size: 8px;}
pre {font-size: 10px}
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F, message = F)
#knitr::opts_knit$set(root.dir = 'C/Users/kloria/Documents/Davis_data_exploration/')
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})

```

```{r, echo = F, message = F}
### Packages
#setwd("C/Users/kloria/Documents/Davis_data_exploration/")

library(tidyverse)
library(lubridate)
library(dataRetrieval)
library(viridis)
library(cowplot)
library(zoo)
library(readxl)
library(ggpubr)
library(knitr)
library(kableExtra)
library(plotly)
library(readxl)
library(ggpmisc)

site_colors <- c(
  "Ophir" = "#7d5ba6",
  "Winters" = "#4287f5",
  "Winters upstream" = "#7fc5f0",
  "Davis" = "#d9cb7c",
  "Browns" = "#c94d00", 
  "Browns sub"  = "#bd772d"
)


site_lab_colors <- c(
  "ophir" = "#7d5ba6",
    "ophir_hw" = "#7d1ba6",
  "winters_usgs" = "#4287f5",
  "winters_up" = "#7fc5f0",
  "davis" = "#d9cb7c",
  "browns" = "#c94d00", 
  "browns_sub"  = "#bd772d",
   "browns_hw"  = "#bd272d"
)


```


```{r, eval=TRUE, echo = F, error=FALSE, warning=FALSE, message=FALSE}
##### Function for water year:
# fxn for water year
water_year <- function(data) {
  data %>%
    mutate(date = ymd(date)) %>%
    mutate(WaterYear = if_else(month(date) >= 10, year(date) + 1, year(date)))
}
```

### Need dates 08/19, 09/10, 9/15 from Davis fire 

Sites: Browns, Browns Sub, Browns Headwaters, Ophir, Ophir Headwaters


## PAck fire - 12/06, hilton 3rd dates on 12/6 and then 12/07 for mcgee 395

Sites: McGee Creek (2nd stop), McGee Park, Mcgee 395, Hilton 


```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}
# Chem data


library(dplyr)
library(lubridate)

davis_dates <- as.Date(c("2025-08-19", "2025-09-10", "2025-09-15", "2025-12-10"))
pack_dates  <- as.Date(c("2025-12-06", "2025-12-07", "2025-12-08"))

ysi_data <- read.csv("/Users/kellyloria/Documents/DRI/ERDC_Davis_Fire/Raw_data/YSI_KOR_dat_20251210_processed.csv") %>%
  mutate(
    datetime = round_date(as.POSIXct(datetime, format = "%Y-%m-%d %H:%M:%S"), unit = "5 minutes"),
    date = as.Date(datetime),
    fire = case_when(
      .data$date %in% davis_dates ~ "Davis",
      .data$date %in% pack_dates  ~ "Pack",
      TRUE ~ NA_character_
    ))


```

```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}

library(dplyr)
library(lubridate)

davis_data <- ysi_data %>%
  filter(fire !="Pack") %>%
  mutate(
    stream = case_when(
      stream == "browns creek" &
        datetime == as.POSIXct("2025-09-15 09:30:00") ~ "browns headwaters",

      stream == "ophir creek" &
        datetime == as.POSIXct("2025-09-15 08:30:00") ~ "ophir headwaters",
      
      # stream == "ophir creek" &
      #   fire == "Pack" &
      #   datetime == as.POSIXct("2025-09-15 08:30:00") ~ "ophir headwaters",

      TRUE ~ stream
    )
  )


names(davis_data)
str(davis_data)
```

### Check long:

```{r, warning=F, size = 'small', echo=FALSE, fig.width=8, fig.height=3}

p1 <- davis_data %>%
  ggplot(aes(x = stream,
             y = long.)) +
  geom_point(
    alpha = 0.8, size = 2, 
    aes(color = stream),
    position = position_jitter(width = 0.1),  
    shape = 19) +
#  scale_fill_manual(values =) +
 # scale_color_manual(values = stream) +
  theme_minimal()

p1

```



### Check lat:

```{r, warning=F, size = 'small', echo=FALSE, fig.width=8, fig.height=3}

p1 <- davis_data %>%
  ggplot(aes(x = stream,
             y = lat.)) +
  geom_point(
    alpha = 0.8, size = 2, 
    aes(color = stream),
    position = position_jitter(width = 0.1),  
    shape = 19) +
  # scale_fill_manual(values = site_lab_colors) +
  # scale_color_manual(values = site_lab_colors) +
  theme_minimal()

p1

```







### remove outlier lat/long/elevation 

```{r, warning=F, size = 'small', echo=FALSE, include=T}

library(dplyr)


davis_dat <- davis_data %>%
  filter(!(stream == "ophir" & altitude_m > 1780)) %>%
    filter(!(stream == "browns" & altitude_m > 1780)) %>%
      filter(!(stream == "browns" & altitude_m < 1600))



davis_data <- davis_data %>%
  mutate(
    stream = case_when(
      abs(lat.  - 39.32994)  < 1e-5 &
      abs(long. - (-119.7965)) < 1e-5 ~ "bizzy beach",
      TRUE ~ stream
    )
  )


# 119.7965, 119.7965
  

p1 <- davis_data %>%
  ggplot(aes(x = stream,
             y = altitude_m)) +
  geom_point(
    alpha = 0.8, size = 2, 
    aes(color = stream),
    position = position_jitter(width = 0.1),  
    shape = 19) +
  # scale_fill_manual(values = site_lab_colors) +
  # scale_color_manual(values = site_lab_colors) +
  theme_minimal()

p1

```

```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}
# write.csv(davis_data, "/Users/kellyloria/Documents/DRI/ERDC_Davis_Fire/Processes_data/ysi_Davis_fire_sites_long_QAQC.csv")

#  write.csv(davis_dat_day, "/Users/kellyloria/Documents/DRI/ERDC_Davis_Fire/Processes_data/ysi_davis_fire_sites_chem.csv")


```

#### Daily means and standard deviations for repeated logged water quality at each site/date 

```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}


davis_dat_day <- davis_data %>%
  group_by(stream, date) %>%
  summarise(
    across(3:22,
           list(mean = ~mean(.x, na.rm = TRUE),
                sd   = ~sd(.x, na.rm = TRUE)),
           .names = "{.col}_{.fn}")
  ) %>%
  ungroup()

```

```{r, warning=F, size = 'small', echo=FALSE, include=T}

p1 <- davis_dat_day %>%
  ggplot(aes(x = date, 
             y = pH_mean,
             color = stream,
             group = stream)) +
#  geom_line(size = 1) +  # connects daily averages over time
  geom_point(size = 2, alpha = 0.9) +  # plot mean points
  geom_errorbar(aes(ymin = pH_mean - pH_sd,
                    ymax = pH_mean + pH_sd),
                width = 0.2, alpha = 0.6) +  # SD error bars
 # scale_color_manual(values = site_lab_colors) +
  labs(x = "Date",
       y = "Ph",
       color = "Site") +
  theme_minimal(base_size = 13) +
  theme(legend.position = "bottom")

p1
```

```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}
# write.csv(davis_dat_day, "/Users/kellyloria/Documents/DRI/ERDC_Davis_Fire/Processes_data/ysi_WQ_QAQC_daily.csv")

```



```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}

library(dplyr)
library(lubridate)


pack_data <- ysi_data %>%
  filter(fire != "Davis") %>%
  mutate(
    stream = case_when(
      stream == "pack" &
        datetime > as.POSIXct("2025-12-07 15:22:00") &   datetime < as.POSIXct("2025-12-08 08:00:00")  ~ "Hilton creek",
      
      stream == "pack" &
        datetime > as.POSIXct("2025-12-07 14:18:00") &   datetime < as.POSIXct("2025-12-07 15:22:00")  ~ "McGee creek",
      
        stream == "pack" &
        datetime > as.POSIXct("2025-12-07 12:00:00") &   datetime < as.POSIXct("2025-12-07 14:10:00")  ~ "McGee park",
      
           stream == "pack" &
        datetime > as.POSIXct("2025-12-08 07:00:00") &   datetime < as.POSIXct("2025-12-08 11:00:00")  ~ "McGee 395",
      
      
      TRUE ~ stream
    )
  )





pack_dat_day <- pack_data %>%
  group_by(stream, date) %>%
  summarise(
    across(3:22,
           list(mean = ~mean(.x, na.rm = TRUE),
                sd   = ~sd(.x, na.rm = TRUE)),
           .names = "{.col}_{.fn}")
  ) %>%
  ungroup()


```


```{r, warning=F, size = 'small', echo=FALSE, include=FALSE}
# write.csv(pack_data, "/Users/kellyloria/Documents/DRI/ERDC_Davis_Fire/Processes_data/ysi_pack_fire_sites_long_QAQC.csv")


#  write.csv(pack_dat_day, "/Users/kellyloria/Documents/DRI/ERDC_Davis_Fire/Processes_data/ysi_pack_fire_sites_chem.csv")



```


End script.



